<script setup lang="ts">
import { onMounted, ref } from 'vue'
import DashboardNav from '@/components/dashboard/DashboardNav.vue'
import ProductForm from '@/components/dashboard/ProductForm.vue'
import { archiveProduct, deleteProduct, getOwnedMerchant, getProducts, saveProduct } from '@/lib/api'
import { formatMoney } from '@/lib/format'
import type { Merchant, Product } from '@/types'
const products=ref<Product[]>([]),merchant=ref<Merchant|null>(null),editing=ref<Product|null>(null),showForm=ref(false),error=ref(''),loading=ref(true),saving=ref(false)
async function load(){loading.value=true;error.value='';try{merchant.value=await getOwnedMerchant();if(merchant.value)products.value=await getProducts(merchant.value.id)}catch(e){error.value=e instanceof Error?e.message:'Products could not be loaded.'}finally{loading.value=false}}
onMounted(load)
async function save(payload:any){if(!merchant.value)return;saving.value=true;error.value='';try{await saveProduct(merchant.value.id,payload,editing.value?.id);showForm.value=false;editing.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'Product could not be saved.'}finally{saving.value=false}}
function edit(p:Product){editing.value=p;showForm.value=true}
async function archive(p:Product){if(!merchant.value)return;error.value='';try{await archiveProduct(merchant.value.id,p.id);await load()}catch(e){error.value=e instanceof Error?e.message:'Product could not be archived.'}}
async function remove(p:Product){if(!merchant.value||!confirm(`Delete ${p.name}?`))return;error.value='';try{await deleteProduct(merchant.value.id,p.id);await load()}catch(e){error.value=e instanceof Error?e.message:'Product could not be deleted.'}}
</script>
<template><div class="min-h-screen bg-paper lg:flex"><DashboardNav/><main class="flex-1 p-4 sm:p-6 lg:p-9"><div class="mx-auto max-w-6xl"><div class="flex items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-muted">Catalogue</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Products</h1><p class="mt-2 text-sm text-muted">Manage the catalogue shoppers can discover and try on.</p></div><button class="min-h-11 rounded-full bg-ink px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" :disabled="loading||!merchant" @click="editing=null;showForm=true">+ Add product</button></div><div v-if="showForm" class="mt-6 rounded-[1.4rem] border border-line bg-white p-5"><h2 class="mb-5 font-semibold">{{editing?'Edit product':'Add product'}}</h2><p v-if="saving" class="mb-3 text-xs text-muted">Saving product…</p><ProductForm :key="editing?.id || 'new'" :product="editing" @save="save" @cancel="showForm=false;editing=null"/></div><p v-if="error" role="alert" class="mt-4 rounded-xl bg-red-50 px-4 py-3 text-xs text-red-700">{{error}}</p><div v-if="loading" class="mt-7 rounded-[1.4rem] border border-line bg-white p-6 text-sm text-muted">Loading catalogue…</div><div v-else-if="!merchant" class="mt-7 rounded-[1.4rem] border border-line bg-white p-6"><h2 class="font-semibold">Catalogue unavailable</h2><p class="mt-2 text-sm text-muted">Sign in with the merchant account that owns this store.</p></div><div v-else-if="products.length" class="mt-7 overflow-hidden rounded-[1.4rem] border border-line bg-white"><div v-for="p in products" :key="p.id" class="flex items-center gap-3 border-b border-line p-3 last:border-0"><img :src="p.primary_image_url" :alt="p.name" class="h-16 w-14 rounded-lg object-cover"/><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{p.name}}</p><p class="mt-1 text-xs text-muted">{{p.category}} · {{p.stock_status.replace('_',' ')}}</p></div><p class="hidden text-sm font-medium sm:block">{{formatMoney(p.price,p.currency)}}</p><div class="flex gap-1 text-xs"><button class="min-h-10 rounded-lg px-2 hover:bg-paper" @click="edit(p)">Edit</button><button class="min-h-10 rounded-lg px-2 hover:bg-paper" @click="archive(p)">Archive</button><button class="min-h-10 rounded-lg px-2 text-red-700 hover:bg-red-50" @click="remove(p)">Delete</button></div></div></div><div v-else class="mt-7 rounded-[1.4rem] border border-dashed border-line bg-white p-8 text-center"><h2 class="font-semibold">Add your first product</h2><p class="mt-2 text-sm text-muted">Your storefront catalogue starts here.</p><button class="mt-5 min-h-11 rounded-full bg-ink px-5 text-xs font-semibold text-white" @click="showForm=true">Add product</button></div></div></main></div></template>
