<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import AppButton from '@/components/ui/AppButton.vue'
import StoreHomeView from '@/views/store/StoreHomeView.vue'
import { customTenantHost } from '@/lib/tenant'

const tenantHost = ref<string | null>(null)
const route = useRoute()
onMounted(() => { tenantHost.value = customTenantHost() })
</script>
<template>
  <StoreHomeView v-if="tenantHost" />
  <main v-else class="min-h-screen bg-paper px-5 py-6 sm:px-8">
    <nav class="mx-auto flex max-w-6xl items-center justify-between"><div class="font-bold tracking-tight">MIRROR</div><div class="flex items-center gap-4"><RouterLink :to="{ path:'/', hash:'#impact' }" class="hidden text-sm font-medium sm:block">Why Mirror</RouterLink><RouterLink to="/pilot" class="text-sm font-medium">Pilot results</RouterLink></div></nav>
    <div v-if="route.query.access==='admin-required'" role="status" class="mx-auto mt-5 max-w-6xl rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900">That dashboard belongs to the pilot retailer. You can view the public <RouterLink to="/pilot" class="font-semibold underline">pilot results</RouterLink> instead.</div>
    <section class="mx-auto grid max-w-6xl gap-10 pb-16 pt-20 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pt-28">
      <div><p class="text-xs font-semibold uppercase tracking-[.22em] text-muted">AI commerce infrastructure for independent fashion</p><h1 class="mt-4 max-w-4xl text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Help a small fashion store sell like a much larger retailer.</h1><p class="mt-6 max-w-2xl text-base leading-7 text-muted sm:text-lg">Mirror turns one retailer’s catalogue into an AI-assisted shopping experience—with virtual try-on, contextual recommendations and measurable purchase intent, inside the retailer’s own brand.</p><div class="mt-8 flex flex-wrap gap-3"><RouterLink to="/store/mirror-atelier"><AppButton>Experience the pilot store</AppButton></RouterLink><RouterLink to="/pilot"><AppButton variant="outline">See the measurable funnel</AppButton></RouterLink></div><p class="mt-5 max-w-xl text-xs leading-5 text-muted">No AR team, recommendation engine or data department required. The retailer brings its catalogue; Mirror provides the intelligence layer.</p></div>
      <div class="rounded-[2rem] bg-ink p-5 text-white sm:p-8"><p class="text-xs uppercase tracking-[.2em] text-white/60">A focused, testable pilot</p><h2 class="mt-3 text-2xl font-semibold tracking-tight">One retailer. One catalogue. Real shopper behaviour.</h2><div class="mt-7 space-y-5 text-base"><p class="grid grid-cols-[2.75rem_minmax(0,1fr)] items-start"><span class="text-white/40">01</span><span>Launch a branded AI shopping experience</span></p><p class="grid grid-cols-[2.75rem_minmax(0,1fr)] items-start"><span class="text-white/40">02</span><span>Let shoppers try, ask and build complete looks</span></p><p class="grid grid-cols-[2.75rem_minmax(0,1fr)] items-start"><span class="text-white/40">03</span><span>Keep every recommendation inside the retailer’s catalogue</span></p><p class="grid grid-cols-[2.75rem_minmax(0,1fr)] items-start"><span class="text-white/40">04</span><span>Measure the path from interest to checkout intent</span></p></div><div class="mt-8 rounded-2xl bg-white/10 p-4 text-sm leading-6 text-white/70">The pilot tests a practical question: can accessible AI help a small fashion business compete for the same shopper confidence larger platforms engineer at scale?</div></div>
    </section>

    <section id="impact" class="mx-auto max-w-6xl border-t border-line py-16 sm:py-20">
      <p class="text-xs font-semibold uppercase tracking-[.22em] text-muted">The gap Mirror closes</p>
      <div class="mt-4 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><h2 class="max-w-xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Personalized commerce should not be reserved for retail giants.</h2><p class="max-w-2xl text-sm leading-7 text-muted sm:text-base">Large e-commerce retailers can invest in AR infrastructure, recommendation systems, personalization teams and sophisticated analytics. Most independent fashion businesses cannot. That technology gap becomes a customer-experience gap—precisely where smaller retailers need to compete.</p></div>
      <div class="mt-10 grid gap-4 md:grid-cols-3">
        <article class="rounded-[1.5rem] border border-line bg-white p-5"><p class="text-[10px] font-semibold uppercase tracking-[.18em] text-muted">Plug in the catalogue</p><h3 class="mt-3 text-lg font-semibold">Use the inventory the business already owns</h3><p class="mt-3 text-sm leading-6 text-muted">Mirror grounds styling and complete-look recommendations in one merchant’s products instead of sending demand to a marketplace competitor.</p></article>
        <article class="rounded-[1.5rem] border border-line bg-white p-5"><p class="text-[10px] font-semibold uppercase tracking-[.18em] text-muted">Add the intelligence</p><h3 class="mt-3 text-lg font-semibold">Offer guided shopping without an AI department</h3><p class="mt-3 text-sm leading-6 text-muted">Virtual try-on and conversational styling help shoppers move from “I like it” to “I can see how I would wear it.”</p></article>
        <article class="rounded-[1.5rem] border border-line bg-white p-5"><p class="text-[10px] font-semibold uppercase tracking-[.18em] text-muted">Measure the outcome</p><h3 class="mt-3 text-lg font-semibold">Turn interactions into an actionable pilot</h3><p class="mt-3 text-sm leading-6 text-muted">The merchant sees try-ons, questions, recommendation engagement and checkout intent—evidence for what to improve and scale next.</p></article>
      </div>
    </section>

    <section class="mx-auto mb-10 max-w-6xl overflow-hidden rounded-[2rem] bg-white p-6 sm:p-10"><div class="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p class="text-xs font-semibold uppercase tracking-[.22em] text-muted">Our objective</p><h2 class="mt-3 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Make advanced AI shopping tools economically reachable for the retailers who need them most.</h2></div><div><p class="text-sm leading-7 text-muted">Mirror is not another fashion marketplace. It is a merchant-owned intelligence layer designed to help small businesses strengthen customer confidence, learn from real demand and keep the path to purchase in their own store.</p><RouterLink to="/store/mirror-atelier" class="mt-5 inline-block text-sm font-semibold underline">Walk through the shopper experience →</RouterLink></div></div></section>
    <footer class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 border-t border-line py-7 text-xs text-muted"><p>Gemini-powered visual styling, grounded in one retailer’s catalogue.</p><div class="flex gap-4"><RouterLink to="/pilot" class="font-medium text-ink">Pilot results</RouterLink><RouterLink to="/privacy" class="font-medium text-ink">Privacy</RouterLink><RouterLink :to="{path:'/auth',query:{redirect:'/dashboard',role:'admin'}}" class="font-medium text-ink">Merchant sign in</RouterLink></div></footer>
  </main>
</template>
