insert into public.products
  (id, merchant_id, name, description, price, currency, category,
   primary_image_url, product_url, sizes, colours, tags, stock_status,
   try_on_category, style_audience, reference_images, visual_description,
   generation_constraints)
values
  ('20000000-0000-4000-8000-000000000017','11111111-1111-4111-8111-111111111111','Charcoal Suit Blazer','Structured two-button men''s suit blazer with notched lapels and a clean tailored line.',58000,'NGN','Blazers','https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-charcoal-suit-blazer.png','https://example.com/mens-charcoal-suit-blazer','["38","40","42","44","46"]','["Charcoal"]','["menswear","tailored","formal","workwear"]','in_stock','outerwear','menswear','[{"view":"front","url":"https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-charcoal-suit-blazer.png"}]','Men''s charcoal structured two-button blazer with notched lapels and flap pockets.','{"preserveColour":true,"preservePattern":true,"preserveLogo":true}'),
  ('20000000-0000-4000-8000-000000000018','11111111-1111-4111-8111-111111111111','White Oxford Shirt','Crisp men''s cotton Oxford shirt with a button-down collar and regular tailored fit.',22000,'NGN','Tops','https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-white-oxford-shirt.png','https://example.com/mens-white-oxford-shirt','["S","M","L","XL","XXL"]','["White"]','["menswear","classic","formal","casual"]','in_stock','top','menswear','[{"view":"front","url":"https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-white-oxford-shirt.png"}]','Men''s crisp white long-sleeve Oxford shirt with button-down collar and chest pocket.','{"preserveColour":true,"preservePattern":true,"preserveLogo":true}'),
  ('20000000-0000-4000-8000-000000000019','11111111-1111-4111-8111-111111111111','Charcoal Tailored Trousers','Men''s flat-front wool trousers with pressed creases and a straight tapered leg.',34000,'NGN','Bottoms','https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-charcoal-tailored-trousers.png','https://example.com/mens-charcoal-tailored-trousers','["30","32","34","36","38","40"]','["Charcoal"]','["menswear","tailored","formal","workwear"]','in_stock','bottom','menswear','[{"view":"front","url":"https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-charcoal-tailored-trousers.png"}]','Men''s charcoal mid-rise flat-front trousers with pressed crease and tapered leg.','{"preserveColour":true,"preservePattern":true,"preserveLogo":true}'),
  ('20000000-0000-4000-8000-000000000020','11111111-1111-4111-8111-111111111111','Dark Brown Derby Shoes','Polished men''s leather Derby shoes with open lacing, almond toes and welted soles.',39000,'NGN','Shoes','https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-dark-brown-derby-shoes.png','https://example.com/mens-dark-brown-derby-shoes','["40","41","42","43","44","45","46"]','["Dark Brown"]','["menswear","formal","classic","leather"]','in_stock','shoes','menswear','[{"view":"front","url":"https://uqflgjddwgabzfxqdlzf.supabase.co/storage/v1/object/public/product-images/catalog-v1/mens-dark-brown-derby-shoes.png"}]','Matching pair of men''s dark brown polished leather Derby shoes with open lacing.','{"preserveColour":true,"preservePattern":true,"preserveLogo":true}')
on conflict (id) do update set
  name=excluded.name, description=excluded.description, price=excluded.price,
  primary_image_url=excluded.primary_image_url, product_url=excluded.product_url,
  sizes=excluded.sizes, colours=excluded.colours, tags=excluded.tags,
  stock_status=excluded.stock_status, is_active=true,
  try_on_category=excluded.try_on_category, style_audience=excluded.style_audience,
  reference_images=excluded.reference_images,
  visual_description=excluded.visual_description,
  generation_constraints=excluded.generation_constraints;
