-- Mirror AI MVP schema
create extension if not exists pgcrypto;

create table public.merchants (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  description text not null default '',
  logo_url text,
  website_url text,
  primary_brand_colour text,
  currency text not null default 'NGN',
  created_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants(id) on delete cascade,
  name text not null,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  currency text not null default 'NGN',
  category text not null,
  primary_image_url text not null,
  product_url text not null,
  sizes jsonb not null default '[]'::jsonb,
  colours jsonb not null default '[]'::jsonb,
  stock_status text not null default 'in_stock' check (stock_status in ('in_stock','low_stock','out_of_stock')),
  tags jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shopper_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  session_id text not null,
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.shopper_images (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  storage_path text not null unique,
  consent_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table public.try_on_generations (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants(id) on delete cascade,
  shopper_user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  shopper_image_id uuid not null references public.shopper_images(id) on delete cascade,
  status text not null default 'preparing' check (status in ('preparing','generating','finalizing','completed','failed')),
  generation_mode text not null default 'single' check (generation_mode in ('single','complete_look')),
  output_storage_path text,
  provider text,
  model text,
  prompt text,
  error text,
  estimated_cost numeric(12,6),
  token_usage jsonb not null default '{}'::jsonb,
  generation_count integer not null default 1,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.try_on_products (
  generation_id uuid not null references public.try_on_generations(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  primary key (generation_id, product_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants(id) on delete cascade,
  shopper_user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  selected_product_id uuid references public.products(id) on delete set null,
  generation_id uuid references public.try_on_generations(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  structured_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants(id) on delete cascade,
  session_id text not null,
  shopper_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  product_id uuid references public.products(id) on delete set null,
  generation_id uuid references public.try_on_generations(id) on delete set null,
  conversation_id uuid references public.conversations(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.rate_limit_events (
  id bigint generated by default as identity primary key,
  bucket text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);
create index rate_limit_events_lookup on public.rate_limit_events(bucket,key_hash,created_at desc);
create index analytics_events_merchant_created on public.analytics_events(merchant_id,created_at desc);
create index analytics_events_type on public.analytics_events(merchant_id,event_type,created_at desc);
create index products_merchant_active on public.products(merchant_id,is_active);
create index generations_user_created on public.try_on_generations(shopper_user_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger products_touch_updated_at before update on public.products for each row execute function public.touch_updated_at();

-- RLS
alter table public.merchants enable row level security;
alter table public.products enable row level security;
alter table public.shopper_profiles enable row level security;
alter table public.shopper_images enable row level security;
alter table public.try_on_generations enable row level security;
alter table public.try_on_products enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.analytics_events enable row level security;
alter table public.rate_limit_events enable row level security;

create policy "merchant storefronts are readable" on public.merchants for select using (true);
create policy "merchant owners insert own store" on public.merchants for insert to authenticated with check (owner_user_id = auth.uid());
create policy "merchant owners update own store" on public.merchants for update to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy "merchant owners delete own store" on public.merchants for delete to authenticated using (owner_user_id = auth.uid());

create policy "active products are public" on public.products for select using (is_active or exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));
create policy "owners insert products" on public.products for insert to authenticated with check (exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));
create policy "owners update products" on public.products for update to authenticated using (exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));
create policy "owners delete products" on public.products for delete to authenticated using (exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));

create policy "shoppers manage own profile" on public.shopper_profiles for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "shoppers manage own image rows" on public.shopper_images for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy "shopper or merchant reads generation" on public.try_on_generations for select to authenticated using (shopper_user_id=auth.uid() or exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));
create policy "shopper or merchant reads generation products" on public.try_on_products for select to authenticated using (exists(select 1 from public.try_on_generations g join public.merchants m on m.id=g.merchant_id where g.id=generation_id and (g.shopper_user_id=auth.uid() or m.owner_user_id=auth.uid())));

create policy "shopper or merchant reads conversations" on public.conversations for select to authenticated using (shopper_user_id=auth.uid() or exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));
create policy "conversation participants read messages" on public.messages for select to authenticated using (exists(select 1 from public.conversations c join public.merchants m on m.id=c.merchant_id where c.id=conversation_id and (c.shopper_user_id=auth.uid() or m.owner_user_id=auth.uid())));

create policy "merchant owner reads analytics" on public.analytics_events for select to authenticated using (exists(select 1 from public.merchants m where m.id=merchant_id and m.owner_user_id=auth.uid()));

-- Private storage buckets. Public product assets can still be read directly.
insert into storage.buckets (id,name,public) values
 ('product-images','product-images',true),
 ('shopper-images','shopper-images',false),
 ('try-on-results','try-on-results',false),
 ('merchant-assets','merchant-assets',true)
on conflict (id) do update set public=excluded.public;

create policy "public reads product images" on storage.objects for select using (bucket_id='product-images');
create policy "owners upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and exists(select 1 from public.merchants m where m.owner_user_id=auth.uid() and m.id::text=(storage.foldername(name))[1]));
create policy "owners manage product images" on storage.objects for update to authenticated using (bucket_id='product-images' and exists(select 1 from public.merchants m where m.owner_user_id=auth.uid() and m.id::text=(storage.foldername(name))[1]));
create policy "owners delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and exists(select 1 from public.merchants m where m.owner_user_id=auth.uid() and m.id::text=(storage.foldername(name))[1]));

create policy "shopper uploads own source images" on storage.objects for insert to authenticated with check (bucket_id='shopper-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "shopper reads own source images" on storage.objects for select to authenticated using (bucket_id='shopper-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "shopper deletes own source images" on storage.objects for delete to authenticated using (bucket_id='shopper-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "shopper reads own tryon results" on storage.objects for select to authenticated using (bucket_id='try-on-results' and (storage.foldername(name))[1]=auth.uid()::text);

create policy "public reads merchant assets" on storage.objects for select using (bucket_id='merchant-assets');
create policy "owners upload merchant assets" on storage.objects for insert to authenticated with check (bucket_id='merchant-assets' and exists(select 1 from public.merchants m where m.owner_user_id=auth.uid() and m.id::text=(storage.foldername(name))[1]));
